export const blogList = [
  {
    id: 1,
    title: "Kozan",
    category: "Restaurants",
    subCategory: ["Agartala", "Food"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "Bodhisatwa Chakraborty",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "December 19 2023",
    cover: "/assets/images/designer-1.jpg",
    slides: [
      "https://i.pinimg.com/originals/51/82/ac/5182ac536727d576c78a9320ac62de30.jpg",
      "https://wallpapercave.com/wp/wp3386769.jpg",
      "https://wallpaperaccess.com/full/809523.jpg",
      "https://getwallpapers.com/wallpaper/full/5/c/0/606489.jpg",
    ],
  },
  {
    id: 2,
    title: "Cafe Frespresso ",
    category: "Restaurants",
    subCategory: ["Agartala", "Food", "Cafe"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "Bodhisatwa Chakraborty",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "December 19 2023",
    cover: "/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg",
    slides: [
      "https://i.pinimg.com/originals/51/82/ac/5182ac536727d576c78a9320ac62de30.jpg",
      "https://wallpapercave.com/wp/wp3386769.jpg",
    ],
  },

  {
    id: 3,
    title: "GIGS MUSIC CAFE",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 4,
    title: "AQUIRALIA CLUB HOUSE",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 5,
    title: "PINK FLAMINGO",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 6,
    title: "COFFEE, TEA & ME",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 7,
    title: "INDI SUTRA",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 8,
    title: "SNAX OH BITE !!",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 9,
    title: "SOCIAL CLUB",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 10,
    title: "PARKLINE",
    category: "Restaurants",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
];
